FROM python:3.7.2-alpine3.8
RUN apt-get update && apt-get install -y \
  pip
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["python", "manage.py", "runserver", “127.0.0.1:8000"]
